### ISSUE TITLE
Chat window should open upon pressing forward slash key

### ISSUE THREAD

**Issue by KevinTyrrell** [GoldpawsStuff/BigInputBox#2]
The default behavior of World of Warcraft when pressing the `/` key is to open a chat box and type `/` into it. This means in order to type: `/BigInputBox`, you would not need to press `ENTER` first. You would simply need to press `/` followed by `BigInputBox`. This should likely be included as those who are used to starting slash commands via `/` instead of `ENTER` will often by instinct press `/` expecting for a chat box to open.

**Comment by Goldpaw** [comment]
Can't do it. We can't put text of any sort into the inputbox without removing its secure status, and thus breaking its ability to cast spells and commands. This is why I've chosen to not redirect that keybind to our box. This is a blizzard limitation.
